### ISSUE TITLE
No way to unset Shipping Address

### ISSUE THREAD

**Issue by KenticoDevTrev** [HBSTech/GenericEcommerce#4]
If shipping option gets set, no way to remove it.  Need to add an additional method / event to removeShippingAddress, and add default javascript to handle the unchecking of the "Shipping address different" checkbox to trigger it.

**Comment by farmergeek94** [comment]
This was resolved with commit c7e336646007a394145f7da13903fff95feac485

**Comment by farmergeek94** [comment]
Actually I was wrong, this was resolved with commit 20a1ed6f48477cd66783d72a8cad831222a46525
